# Nome da Actions:  
name: Snake Game

# Controlador do tempo que será feito a atualização dos arquivos.
on:
  schedule:
    # Será atualizado a cada 5 horas.
    - cron: "0 */5 * * *"

  workflow_dispatch:

# Regras
jobs:
  build:
    runs-on: ubuntu-latest
    steps:

      # Usar a versão mais recente do actions/checkout
      - uses: actions/checkout@v3

      # Usar a ação Platane/snk para gerar os arquivos GIF e SVG da cobra
      - uses: Platane/snk@master
        id: snake-gif
        with:
          github_user_name: jonatapontesdev # Substitua pelo seu nome de usuário correto
          gif_out_path: dist/github-contribution-grid-snake.gif
          svg_out_path: dist/github-contribution-grid-snake.svg

      # Verifica o status do repositório
      - run: git status

      # Atualiza a ação github-push-action para uma versão mais recente
      - name: Push changes
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "Atualizando grid da cobra"
          branch: master
          file_pattern: dist/*

      # Atualiza a ação de deploy para o GitHub Pages
      - name: Deploy to GitHub Pages
        uses: crazy-max/ghaction-github-pages@v3
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
