name: Generate Snake Contribution Grid

on:
  schedule:
    - cron: "0 0 * * *"  # Runs every day at midnight
  workflow_dispatch:

jobs:
  generate:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Generate the snake animation with custom palette
      - name: Generate the snake animation
        uses: Platane/snk@v3
        with:
          github_user_name: jonatapontesdev
          outputs: |
            dist/github-snake.svg
            dist/github-snake-dark.svg?palette=github-dark
            dist/github-snake-custom.svg?color_snake=orange&color_dots=#d1c089,#ab843d,#ba9f69,#8b6d1d,#6a4e0a

      # Optional: List generated files
      - name: List output files
        run: ls -R dist

      # Deploy the animation to GitHub Pages
      - name: Deploy to GitHub Pages
        uses: crazy-max/ghaction-github-pages@v2.1.3
        with:
          target_branch: output
          build_dir: dist
        env:
          GH_PAT: ${{ secrets.GH_PAT }}
